version: '3.8'
services:
  db:
    image: keinos/sqlite3
    volumes:
      - ./data:/data
  backend:
    build: ./backend
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - POCSAG_USER=${POCSAG_USER}
      - POCSAG_PASS=${POCSAG_PASS}
    volumes:
      - ./backend:/app
      - ./data:/data
    ports:
      - '3000:3000'
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '5173:80'
    depends_on:
      - backend
