version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb
      JWT_SECRET: changeme
    depends_on:
      - db
    ports:
      - '3000:3000'
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '5173:80'
volumes:
  db-data:
